name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: adopt

      - name: Install dependencies
        run: mvn clean install

      - name: Run tests
        run: mvn test

      - name: Build project
        run: mvn package

      - name: Archive build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: trade-store-artifacts
          path: target/*.jar

